language: ruby
before_install:
  - gem install --no-ri --no-rdoc coveralls -v '~> 0.8'
  - gem install --no-ri --no-rdoc bashcov -v '~> 1.3'
  - cd $TRAVIS_BUILD_DIR
script:
  - make coverage
cache:
  directories:
  - opt
notifications:
  email:
    on_success: never
