language: bash
before_install:
  - gem install coveralls
  - gem install bashcov
  - cd $TRAVIS_BUILD_DIR
script:
  - bashcov make test
cache:
  directories:
  - opt
notifications:
  email:
    on_success: never
