language: bash
before_install:
  - bash --version
  - gem --version
  - gem install coveralls
  - gem install bashcov
  - cd $TRAVIS_BUILD_DIR
script:
  - make coverage
cache:
  directories:
  - opt
notifications:
  email:
    on_success: never
