language: ruby
matrix:
  include:
    - os: linux
      env: RECIPE=coverage
    - os: osx
      env: RECIPE=test
script:
  - make $RECIPE
cache:
  directories:
    - .Makefile.d
    - ./.reqd/opt
notifications:
  email:
    on_success: never
